docker:image:
  image: docker:stable
  services:
    - docker:dind
  only:
    - tags
    - master
    - web
  script:
    - echo Building: ${IMAGE_TAG:=${CI_BUILD_TAG:-$([ $CI_COMMIT_REF_NAME == "master" ] && echo "latest" || echo "$CI_COMMIT_REF_SLUG")}}
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG