image: docker:stable

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - "[[ -n $CI_BUILD_TAG ]] && docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_BUILD_TAG"

deploy:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest
    - "[[ -n $CI_BUILD_TAG ]] && docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG"
